BookStore/Controllers/PurchaseController.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{

    //Controller for the purchases
    public class PurchaseController : Controller
    {

        private IPurchaseRepository repo { get; set; }
        private Basket basket { get; set; }

        public PurchaseController(IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {

            //Only allow a purchase if cart has contents
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {

                //Add to database
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }
        }
    }
}

BookStore/Pages/Buy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Infrastructure;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookStore.Pages
{
    public class BuyModel : PageModel
    {

        private IBookStoreRepository repo { get; set; }
        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }

        public BuyModel (IBookStoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }


        //returns buy page view
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }


        //Adds item to the basket
        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl});
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x =>  x.Book.BookId == bookId).Book);

            return RedirectToPage ( new {ReturnUrl = returnUrl});
        }
    }
}

BookStore/Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookStore.Pages
{
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BookStore/Pages/Buy.cshtml
@page
@model BookStore.Pages.BuyModel
@{
}


@* This view creates the table for the shopping cart, showing each item
    to be purchased with quantity and price, and the total price. *@

@* Added progress bar *@
<div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuenow="70"
         aria-valuemin="0" aria-valuemax="100" style="width:33%">
        <span class="sr-only"></span>
    </div>
</div>

<h2>Your Cart</h2>

@* Here I added a bootstrap feature to make the table rows hoverable with table-hover *@
<table class="table table-bordered table-striped table-hover table-dark">

    <thead>
        <tr>
            <th class="col-5">Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>

        @* iterate through each book in basket and display attributes *@
        @foreach (var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>$@i.Book.Price</td>
                <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId"/>
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl"/>
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>



</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
</div>

BookStore/Pages/PurchaseCompleted.cshtml
@page
@model BookStore.Pages.PurchaseCompletedModel
@{
}

<div class="text-center">
    <h2>Your order has been confirmed.</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

BookStore/Pages/_BuyLayout.cshtml
<!DOCTYPE html>

@* This page creates the shared Buy view, where the user can see their shopping cart *@

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/lib/css/bootstrap-utilities.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        Book Store
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>