BookStore/Components/CartSummaryViewComponent.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Components
{

    //Helps us build the cart summary
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        public CartSummaryViewComponent(Basket basketService)
        {
            basket = basketService;
        }
        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

BookStore/Components/CategoriesViewComponent.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Components
{

    //This class helps us view the books filtered by category
    public class CategoriesViewComponent : ViewComponent
    {
        private IBookStoreRepository repo { get; set; }
        public CategoriesViewComponent (IBookStoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"];


            //only show those books with a specific category
            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

BookStore/Views/Shared/BookSummary.cshtml
@{
}

@model Book



<div class="card card-outline-primary m-1 p-1">


    @* Display each book *@
    <div class="bg-light p-1">
        <h4>@Model.Title, by @Model.Author</h4>

        <span class="badge bg-info" style="float:right">
            Price: $@Model.Price
        </span>
    </div>

    <ul>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>Page Count: @Model.PageCount</li>

    </ul>


    @*  Add to cart button adds the book to cart*@
    <form method="post" asp-page="/Buy">
        <input type="hidden" asp-for="@Model.BookId"/>
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>
    </form>
</div>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/lib/css/bootstrap-utilities.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />


</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Book Store</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    @*<div class="bg-dark text-white p-2" text>
        <span class="navbar-brand m-lg-2"></span>
    </div>*@

    <div class="row m-1 p-1">

        <div id="types" class="col-3">
            <vc:categories></vc:categories>
        </div>
        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>

    </div>



</body>
</html>